/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/opengl/GLEmitter.java on Fri Aug 03 06:28:50 CEST 2012 ----! */

package jogamp.opengl.x11.glx;

import java.util.*;
import javax.media.opengl.*;
import javax.media.opengl.fixedfunc.*;
import jogamp.opengl.*;
import jogamp.nativewindow.x11.*;
import com.jogamp.gluegen.runtime.ProcAddressTable;

/**
 * This table is a cache of pointers to the dynamically-linkable C library.
 * @see ProcAddressTable
 */
public class GLXExtProcAddressTable extends ProcAddressTable {

  public long _addressof_glMapBuffer;

  public GLXExtProcAddressTable(){ super(); }

  public GLXExtProcAddressTable(com.jogamp.gluegen.runtime.FunctionAddressResolver resolver){ super(resolver); }

  public long _addressof_glXAllocateMemoryNV;
  public long _addressof_glXBindChannelToWindowSGIX;
  public long _addressof_glXBindSwapBarrierNV;
  public long _addressof_glXBindSwapBarrierSGIX;
  public long _addressof_glXBindTexImageEXT;
  public long _addressof_glXBindVideoDeviceNV;
  public long _addressof_glXBindVideoImageNV;
  public long _addressof_glXChannelRectSGIX;
  public long _addressof_glXChannelRectSyncSGIX;
  public long _addressof_glXCopySubBufferMESA;
  public long _addressof_glXCreateContextAttribsARB;
  public long _addressof_glXCushionSGI;
  public long _addressof_glXEnumerateVideoDevicesNV;
  public long _addressof_glXFreeContextEXT;
  public long _addressof_glXFreeMemoryNV;
  public long _addressof_glXGetAGPOffsetMESA;
  public long _addressof_glXGetContextIDEXT;
  public long _addressof_glXGetCurrentDisplayEXT;
  public long _addressof_glXGetCurrentReadDrawableSGI;
  public long _addressof_glXGetMscRateOML;
  public long _addressof_glXGetProcAddress;
  public long _addressof_glXGetProcAddressARB;
  public long _addressof_glXGetRefreshRateSGI;
  public long _addressof_glXGetSyncValuesOML;
  public long _addressof_glXGetTransparentIndexSUN;
  public long _addressof_glXGetVideoDeviceNV;
  public long _addressof_glXGetVideoInfoNV;
  public long _addressof_glXGetVideoSyncSGI;
  public long _addressof_glXImportContextEXT;
  public long _addressof_glXJoinSwapGroupNV;
  public long _addressof_glXJoinSwapGroupSGIX;
  public long _addressof_glXMakeCurrentReadSGI;
  public long _addressof_glXQueryChannelDeltasSGIX;
  public long _addressof_glXQueryChannelRectSGIX;
  public long _addressof_glXQueryContextInfoEXT;
  public long _addressof_glXQueryFrameCountNV;
  public long _addressof_glXQueryMaxSwapBarriersSGIX;
  public long _addressof_glXQueryMaxSwapGroupsNV;
  public long _addressof_glXQuerySwapGroupNV;
  public long _addressof_glXReleaseBuffersMESA;
  public long _addressof_glXReleaseTexImageEXT;
  public long _addressof_glXReleaseVideoDeviceNV;
  public long _addressof_glXReleaseVideoImageNV;
  public long _addressof_glXResetFrameCountNV;
  public long _addressof_glXSendPbufferToVideoNV;
  public long _addressof_glXSet3DfxModeMESA;
  public long _addressof_glXSwapBuffersMscOML;
  public long _addressof_glXSwapIntervalSGI;
  public long _addressof_glXWaitForMscOML;
  public long _addressof_glXWaitForSbcOML;
  public long _addressof_glXWaitVideoSyncSGI;
  /**
   * This is a convenience method to get (by name) the native function
   * pointer for a given function. It lets you avoid having to
   * manually compute the &quot;_addressof_ + 
   * &lt;functionName&gt;&quot; member variable name and look it up via
   * reflection; it also will throw an exception if you try to get the
   * address of an unknown function, or one that is statically linked
   * and therefore does not have a function pointer in this table.
   *
   * @throws RuntimeException if the function pointer was not found in
   *   this table, either because the function was unknown or because
   *   it was statically linked.
   */
  public long getAddressFor(String functionNameUsr) {
    String functionNameBase = com.jogamp.gluegen.runtime.opengl.GLNameResolver.normalizeVEN(com.jogamp.gluegen.runtime.opengl.GLNameResolver.normalizeARB(functionNameUsr, true), true);
    String addressFieldNameBase = PROCADDRESS_VAR_PREFIX + functionNameBase;
    java.lang.reflect.Field addressField = null;
    int  funcNamePermNum = com.jogamp.gluegen.runtime.opengl.GLNameResolver.getFuncNamePermutationNumber(functionNameBase);
    for(int i = 0; null==addressField && i < funcNamePermNum; i++) {
        String addressFieldName = com.jogamp.gluegen.runtime.opengl.GLNameResolver.getFuncNamePermutation(addressFieldNameBase, i);
        try {
          addressField = getClass().getField(addressFieldName);
        } catch (Exception e) { }
    }

    if(null==addressField) {
      // The user is calling a bogus function or one which is not
      // runtime linked
      throw new RuntimeException(
          "WARNING: Address field query failed for \"" + functionNameBase + "\"/\"" + functionNameUsr +
          "\"; it's either statically linked or address field is not a known " +
          "function");
    } 
    try {
      return addressField.getLong(this);
    } catch (Exception e) {
      throw new RuntimeException(
          "WARNING: Address query failed for \"" + functionNameBase + "\"/\"" + functionNameUsr +
          "\"; it's either statically linked or is not a known " +
          "function", e);
    }
  }
} // end of class GLXExtProcAddressTable
